name: CI

env:
  DOTNET_VERSION: 8.0.x


on:
  push:
    branches:
       - main
       - fix/**
       - feat/**

jobs:
  build:
    environment:
      name: 'prod'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=docker.io -p ContainerRepository=miiitch/mpelabs.dnslookup-dev
      working-directory: src/mpelabs.dnslookup

    
    
