name: Release

env:
  DOTNET_VERSION: 8.0.x


on:
  push:
    tags:
      - '[0-9]\.[0-9]+\.[0-9]+'

jobs:
  build:
    if:  github.event.base_ref == 'refs/heads/main'
    environment:
      name: 'prod'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=docker.io -p AssemblyVersion=$GITHUB_REF_NAME -p ContainerRepository=miiitch/mpelabs.dnslookup -p ContainerImageTags=latest;$GITHUB_REF_NAME;$GITHUB_SHA
      working-directory: src/mpelabs.dnslookup

    
    
